### ISSUE TITLE
[BUG] version number added as float

### ISSUE THREAD

**Issue by Anthchirp** [conda-incubator/grayskull#192]
**Describe the bug**
I used https://www.marcelotrevisani.com/grayskull to create a recipe for [`executing`](https://pypi.org/project/executing) 0.5.3, which resulted in:

```yaml
{% set name = "executing" %}
{% set version = 0.5.3 %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c039c841e0b606fca7774b42302697b2f0eca78b4d0e3e582024cf881776379
(...)
```
and no further occurrences of `{{ version }}` (PR conda-forge/executing-feedstock#3)

This recipe resulted in [a build failure](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=226760&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97) due to
```
INFO:conda_build.metadata:Attempting to finalize metadata for executing
Error: Failed to render jinja template in /home/conda/recipe_root/meta.yaml:
float object has no element 3
```

I then replaced
```patch
-{% set version = 0.5.3 %}
+{% set version = "0.5.3" %}
```
and the build [succeeded](https://github.com/conda-forge/executing-feedstock/pull/3/commits/73bcc338012288e2647dc83b531c366aedc945d3).

I guess version numbers shouldn't be treated as numbers?
