### ISSUE TITLE
[BUG] console_scripts entry_points are not extracted

### ISSUE THREAD

**Issue by BastianZim** [conda-incubator/grayskull#212]
**Describe the bug**

`console_scripts entry_points` cannot be extracted when not formatted as a dictionary. 

The format which fails: 

```yaml
entry_points="""
    [console_scripts]
    awslimitchecker = awslimitchecker.runner:console_entry_point
    """
```

**To Reproduce**
1. Create a recipe for a formula that has `entry_points` formatted as above.
2. ` entry_points` is not extracted

**Expected behavior**

The `build` section should have an `entry_points` section:

```yaml
build:
  entry_points:
  - awslimitchecker = awslimitchecker.runner:console_entry_point
```

**Outputs**
If applicable, add the output to help explain your problem.

Current output:
```yaml
{% set name = "awslimitchecker" %}
{% set version = "10.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awslimitchecker-{{ version }}.tar.gz
  sha256: 7610ac0fbe0817754e238099053a4ff4d3ea5260676094af86331891d6934a09

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - boto3 >=1.9.175
    - botocore
    - python
    - python-dateutil
    - pytz
    - termcolor >=1.1.0
    - urllib3
    - versionfinder >=0.1.1

test:
  imports:
    - awslimitchecker
    - awslimitchecker.alerts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jantman/awslimitchecker
  summary: A script and python module to check your AWS service limits and usage, and warn when usage approaches limits.
  license: AGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ADD_YOUR_GITHUB_ID_HERE
```

**Environment:**
Not dependent on environment

**Additional context**

This has been verified with two packages: https://github.com/conda-forge/staged-recipes/pull/13849 (Original [`entry_points`](https://github.com/developmentseed/morecantile/blob/4f1041daae3cadb6dcf6c11eee515c521b637665/setup.py#L43-L46)) and https://github.com/conda-forge/staged-recipes/pull/13848 (Original [`entry_points`](https://github.com/jantman/awslimitchecker/blob/645e22dbe98841421c095837b621eb1188b732a2/setup.py#L81-L84))

Can also be reproduced by entering `awslimitchecker` into https://www.marcelotrevisani.com/grayskull

cc @ocefpaf and @lsetiawan
