### ISSUE TITLE
[FEATURE] Be aware of empty packages for certain python versions

### ISSUE THREAD

**Issue by BastianZim** [conda-incubator/grayskull#216]
**Is your feature request related to a problem? Please describe.**

Some packages on conda-forge are empty for specific python versions (one example here is [dataclasses](https://github.com/conda-forge/dataclasses-feedstock/blob/master/recipe/meta.yaml)) as they contain features added to later python versions.
The empty packages were added since the package that depends on them could otherwise not be `noarch: python`.
Currently, Grayskull still recommends skipping those packages for the python versions where they aren't needed anymore, even if the packages are actually empty.

One example here is the output of _transformers_:

```yaml
{% set name = "transformers" %}
{% set version = "4.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/transformers-{{ version }}.tar.gz
  sha256: 48d6cc3ab40c901b9ce803d3b445ff88f023150dde7b36bf834829bca759b7fd

build:
  number: 0
  skip: true   # [py2k]
  entry_points:
    - transformers-cli=transformers.commands.transformers_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - dataclasses  # [py<37]
    - filelock
    - importlib-metadata  # [py<38]
    - numpy >=1.17
    - packaging
    - python
    - regex !=2019.12.17
    - requests
    - sacremoses
    - tokenizers >=0.10.1,<0.11
    - tqdm >=4.27

test:
  imports:
    - transformers
    - transformers.benchmark
  commands:
    - pip check
    - transformers-cli --help
  requires:
    - pip

about:
  home: https://github.com/huggingface/transformers
  summary: State-of-the-art Natural Language Processing for TensorFlow 2.0 and PyTorch
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ADD_YOUR_GITHUB_ID_HERE

```

**Describe the solution you'd like**

Grayskull should be aware of empty packages and not add a skip statement, even if upstream demands it.

**Describe alternatives you've considered**
None

**Additional context**

It might be nice to have this in a database that is also linked in the docs. I have opened https://github.com/conda-forge/conda-forge.github.io/issues/1270 to reflect this.
