### ISSUE TITLE
[FEATURE] Extract `python_requires` from _setup.py_

### ISSUE THREAD

**Issue by BastianZim** [conda-incubator/grayskull#227]
**Is your feature request related to a problem? Please describe.**

Currently, the minimum python version is only extracted from _setup_cfg_: https://github.com/conda-incubator/grayskull/search?q=python_requires 

**Describe the solution you'd like**

Not all packages have that so it would be good if it could also be read from _setup.py_.

**Describe alternatives you've considered**

None

**Additional context**

One example is https://github.com/bojiang/typing_utils/blob/main/setup.py which has `python_requires=">=3.6.1",`

Generated _meta.yaml_ is:

```yaml
{% set name = "typing_utils" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typing_utils-{{ version }}.tar.gz
  sha256: 8ff6b6705414b82575ad5ae0925ac414a9650fb8c5718289b1327dec61252f65

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - typing_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bojiang/typing_utils
  summary: utils to inspect Python type annotations
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ADD_YOUR_GITHUB_ID_HERE
```
