### ISSUE TITLE
[BUG] selectors have extra spaces

### ISSUE THREAD

**Issue by xylar** [conda-incubator/grayskull#380]
**Describe the bug**
In the latest release (1.8.0) it seems that something changed where selectors now have `(2 spaces)#(2 spaces)` instead of the `(2 spaces)#(1 space)` desired by the conda-forge linter.

**To Reproduce**
```
grayskull pypi poetry
```
Look at the selectors

**Expected behavior**
Selectors should have one space, not 2 after the hash.

**Outputs**
``` yaml
$ cat poetry/meta.yaml 
{% set name = "poetry" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poetry-{{ version }}.tar.gz
  sha256: 17c527d5d5505a5a7c5c14348d87f077d643cf1f186321530cde68e530bba59f

build:
  skip: true  # [py>=400 or py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - ansible
    - pip
  run:
    - python
    - dulwich >=0.20.44,<0.21.0
    - urllib3 >=1.26.0,<2.0.0
    - xattr >=0.9.7,<0.10.0  #  [darwin]
    - virtualenv
    - tomlkit >=0.11.1,<1.0.0,!=0.11.2,!=0.11.3
    - shellingham >=1.5,<2.0
    - requests-toolbelt >=0.9.1,<0.10.0
    - requests >=2.18,<3.0
    - platformdirs >=2.5.2,<3.0.0
    - pkginfo >=1.5,<2.0
    - pexpect >=4.7.0,<5.0.0
    - packaging >=20.4
    - keyring >=21.2.0
    - jsonschema >=4.10.0,<5.0.0
    - importlib-metadata >=4.4,<5.0  #  [py<310]
    - html5lib >=1.0,<2.0
    - crashtest >=0.3.0,<0.4.0
    - cleo >=1.0.0a5,<2.0.0
    - cachy >=0.3.0,<0.4.0
    - cachecontrol >=0.12.9,<0.13.0
    - poetry-plugin-export >=1.0.6,<2.0.0
    - poetry-core ==1.1.0

test:
  imports:
    - poetry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://python-poetry.org/
  summary: Python dependency management and packaging made easy.
  license: MIT
  license_file:
    - LICENSE
    - tests/fixtures/with-include/LICENSE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere

```
**Environment:**
 ```
$ grayskull --version
1.8.0
```
