### ISSUE TITLE
[BUG] requirements needed with outputs

### ISSUE THREAD

**Issue by woutdenolf** [conda-incubator/grayskull#382]
Conda forge fails with the message `'PYTHON' is undefined` when the `outputs` section is defined (i.e. extra requires).

The reason is this

```yaml
outputs:
  - name: pypushflow
    requirements:
      host: &id001
        - python >=3.6
        - pip
      run:
        - python >=3.6
  - name: pypushflow-mx
    requirements:
      host: *id001
      run:
        - pypushflow =={{ version }}
        - pymongo >=4
```

which should become

```yaml
requirements: # !!!!
  host:
    - python >=3.6
    - pip

outputs:
  - name: pypushflow
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
  - name: pypushflow-mx
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6  # !!!!!
        - pypushflow =={{ version }}
        - pymongo >=4
```

Command:

```
grayskull pypi pypushflow --extras-require-all --extras-require-split --extras-require-test test --extras-require-exclude dev --strict-conda-forge
```
