### ISSUE TITLE
[BUG] metadata package name wrong when the recipe has multuiple outputs

### ISSUE THREAD

**Issue by woutdenolf** [conda-incubator/grayskull#383]
For example

```
grayskull pypi pypushflow --extras-require-all --extras-require-split --extras-require-test test --extras-require-exclude dev --strict-conda-forge
```

gives this

```yaml
{% set name = "pypushflow" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
```

but it should be this

```yaml
{% set name = "pypushflow" %}

package:
  name: {{ name|lower }}-meta  # !!!!
  version: {{ version }}
```

The reason is this part of the code (it only uses the version, not the name):

```
def update_recipe(recipe: Recipe, config: Configuration, all_sections: List[str]):
            if section == "package":
                set_global_jinja_var(recipe, "version", metadata["package"]["version"])
                config.version = metadata["package"]["version"]
                recipe["package"]["version"] = "<{ version }}"
```
