### ISSUE TITLE
[BUG] names of multiple outputs vs package name

### ISSUE THREAD

**Issue by woutdenolf** [conda-incubator/grayskull#388]
https://github.com/conda-forge/matplotlib-feedstock/blob/main/recipe/meta.yaml

```
package:
    name: matplotlib-suite

outputs:
    name: matplotlib-base  # has files

    name: matplotlib  # has no files
```

However when I try this myself for another package, none of the outputs have files

https://github.com/conda-forge/pypushflow-feedstock/blob/main/recipe/meta.yaml

```
package:
    name: pypushflow-meta

outputs:
    name: pypushflow  # has no files

    name: pypushflow-mx  # has no files
```

I traced through the `conda build` code and found this:

https://github.com/conda/conda-build/blob/432a9e1b41a3dec8f95a7556632f9a93fdf029fd/conda_build/build.py#L2274

So it seems that to have files bundled with an output, the output name must be equal to the package name.

In that case I don't understand how `matplotlib`.

In any case, `grayskull` should probably produce this

```
package:
    name: mypackage

outputs:
    name: mypackage  # has files

    name: mypackage-extra  # has no files
```

**Comment by marcelotrevisani** [comment]
https://github.com/conda-forge/matplotlib-feedstock/blob/2ca6433797f0a4f77fee890c6fa39617a6a6b0b4/recipe/meta.yaml#L20

**Comment by marcelotrevisani** [comment]
so as you are trying to have multiple outputs with different run requirements. You will need to add the main package name to the outputs run requirements, so it will fetch and install that package plus the other dependencies that you need

**Comment by woutdenolf** [comment]
> you need to specify in the recipe how to build the package, as it was like another recipe,

You mean `you need to specify in the output how to build the package, as it was like another recipe`?

**Comment by marcelotrevisani** [comment]
> > you need to specify in the recipe how to build the package, as it was like another recipe,
> 
> You mean `you need to specify in the output how to build the package, as it was like another recipe`?

yup, pretty much it, because an output will be basically another package. So, you need to instruct conda build how to create that other package

**Comment by woutdenolf** [comment]
So is this the case?

```
package:
    name: mypackage

outputs:
    name: mypackage  # this inherits top-level sections like build and test

    name: mypackage-extra  # this does not inherit anything
```
