### ISSUE TITLE
[FEATURE] support platform specific dependencies

### ISSUE THREAD

**Issue by woutdenolf** [conda-incubator/grayskull#390]
Setuptools:

```yaml
# setup.cfg

[options]
    importlib_resources; python_version < "3.7"
```

Conda (not sure but whatever the equivalent is):

```yaml
# meta.yaml

requirements:
    run:
        - importlib_resources # [py>=37]
```
