### ISSUE TITLE
[BUG] python_version<"x.y" affects noarch and python run constraints?

### ISSUE THREAD

**Issue by woutdenolf** [conda-incubator/grayskull#408]
```
grayskull pypi ewoksjob==0.0.10rc0
grayskull pypi ewoksjob==0.0.10rc1
```

Version `0.0.10rc1` added this dependency

```
`importlib-metadata<5.0; python_version<"3.8"`
```

The recipe of  `0.0.10rc0` looks normal

```yaml
{% set name = "ewoksjob" %}
{% set version = "0.0.10rc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ewoksjob-{{ version }}.tar.gz
  sha256: 2b35acfef0c34e9c5aaf5db9a97d97d801c915976ab8e93bed45ff77b7df782b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - celery >=5
    - ewoksutils >=0.1

test:
  imports:
    - ewoksjob
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.esrf.fr/workflow/ewoks/ewoksjob/
  summary: Asynchronous and distributed scheduling of Ewoks workflows from python
  dev_url: https://gitlab.esrf.fr/workflow/ewoks/ewoksjob/
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - woutdenolf
```

The recipe of  `0.0.10rc1` has problems (`python >= 3.6` is missing and `noarch` is missing as well)

```yaml
{% set name = "ewoksjob" %}
{% set version = "0.0.10rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ewoksjob-{{ version }}.tar.gz
  sha256: 58d1a9c10d7d620dba9b45b77bd4e21e79555e67c62395565a5937a0e83d9c48

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - celery >=5
    - importlib-metadata <5.0  # [py<38]
    - ewoksutils >=0.1

test:
  imports:
    - ewoksjob
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.esrf.fr/workflow/ewoks/ewoksjob/
  summary: Asynchronous and distributed scheduling of Ewoks workflows from python
  dev_url: https://gitlab.esrf.fr/workflow/ewoks/ewoksjob/
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - woutdenolf
```
