### ISSUE TITLE
[BUG] Multi output not working for _Lark_

### ISSUE THREAD

**Issue by BastianZim** [conda-incubator/grayskull#414]
**Describe the bug**

When running `--extras-require-split` the extras should be outputted as a separate package but nothing happens 

**To Reproduce**
1. Run `grayskull pypi --strict-conda-forge --extras-require-split Lark

**Expected behavior**

The `extras_require` from upstream is listed as a separate package.

**Outputs**
If applicable, add the output to help explain your problem.

**Environment:**
 - conda list
 - pip list
 - grayskull --version

```yaml
{% set name = "Lark" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lark-{{ version }}.tar.gz
  sha256: eee86062b149600ef62de0d8dfd38cf85ffc737e16911e7d8c18880f8c5b1333

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6

test:
  imports:
    - lark
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lark-parser/lark
  summary: a modern parsing library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
```

Version: 1.8.4

**Additional context**

Upstream: https://github.com/lark-parser/lark/blob/master/setup.py
