### ISSUE TITLE
[BUG] Minimum python version in host is dropped

### ISSUE THREAD

**Issue by BastianZim** [conda-incubator/grayskull#430]
**Describe the bug**

The host python does not have a minimum python in noarch packages.

**To Reproduce**
1. Create recipe with `grayskull pypi --strict-conda-forge py3dns`

**Expected behavior**

Host and run python has minimum version 

**Outputs**
If applicable, add the output to help explain your problem.

```yaml
{% set name = "py3dns" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py3dns-{{ version }}.tar.gz
  sha256: 1f07d4463e98d9859ce0280c3eaa57da670ad623f6d4d3285c67dca23d7045e4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6

test:
  imports:
    - DNS
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://launchpad.net/py3dns
  summary: Python 3 DNS library
  license: LGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
```

**Environment:**
Grayskull version: 2.1.0

**Additional context**
